name: automei
description: A new Flutter project.
publish_to: none
version: 0.0.6
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.6.0
  firebase_auth: ^3.1.0
  firebase_storage: ^10.0.3
  firebase_analytics: ^8.3.1
  firebase_crashlytics: ^2.2.1
  cloud_firestore: ^2.5.1
  flutter_signin_button: ^2.0.0
  google_sign_in: ^5.1.0
  flutter_facebook_auth: ^3.5.1
  image_picker: ^0.8.4
  extended_masked_text: ^2.3.1
  uuid: ^3.0.4
  intl: ^0.17.0
  github_sign_in: ^0.0.5-dev.1
  url_launcher: ^6.0.10
  flutter_stripe: ^1.3.0
  facebook_audience_network: ^1.0.0-nullsafety.0
  http: ^0.13.3
  provider: ^6.0.0
  google_mobile_ads: ^0.13.4
  firebase_remote_config: "^0.10.0+4"
  onesignal_flutter: ^3.2.3
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/images/ic_launcher.png
    - assets/images/icon_solo.png
    - assets/images/logo.png
    - assets/images/search.png
    - assets/images/facebook.png
    - assets/images/github.png
    - assets/images/whatsapp.png
    - assets/images/undraw_data_reports_706v.png
    - assets/images/GPay.png
    - assets/config/google.json
    - assets/images/checked (1).png
